---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# corona19

R package for import datasets of Coronavirus disease 2019 in South Korea from [Data-Science-for-COVID-19](https://github.com/jihoo-kim/Coronavirus-Dataset).

---



## Installation

``` r
# install.packages("remotes")
remotes::install_github("youngwoos/corona19")
```


## Example

```{r example, message=FALSE, warning=F}
library(corona19)

# time
time <- getdata("time")
time

library(ggplot2) 
ggplot(data = time, aes(x = date, y = confirmed)) + 
  geom_area(color="darkblue", fill="lightblue") + 
  scale_x_date(date_breaks = "weeks" , date_labels = "%m-%d")

# patient
patient <- getdata("patient") 
patient

ggplot(data = patient, aes(x = 2020-birth_year, fill = sex, colour = sex)) + 
  geom_density(alpha = 0.3) +
  xlab("age")

# route
route <- getdata("route") 

library(dplyr)
cnt_province <- route %>% 
  count(province, sort = T) %>% 
  head(10)

cnt_province

ggplot(cnt_province, aes(x = reorder(province, n), y = n)) + 
  geom_col() + 
  coord_flip() +
  xlab("province")
```

## Dataset infomation

[dataset-detailed-description.ipynb](https://github.com/jihoo-kim/Data-Science-for-COVID-19/blob/master/dataset-detailed-description.ipynb)

`getdata()` import 3 of these datasets.

- `patient` from [PatientInfo.csv](https://github.com/jihoo-kim/Data-Science-for-COVID-19/raw/master/dataset/Patient/PatientInfo.csv)
- `route` from [PatientRoute.csv](https://github.com/jihoo-kim/Data-Science-for-COVID-19/raw/master/dataset/Patient/PatientRoute.csv)
- `time` from [Time.csv](https://github.com/jihoo-kim/Data-Science-for-COVID-19/raw/master/dataset/Time/Time.csv)
